// <auto-generated />
using cafeWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace cafeWeb.Migrations
{
    [DbContext(typeof(myDbContext))]
    partial class myDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("cafeWeb.Models.Admin", b =>
                {
                    b.Property<int>("admid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Phone");

                    b.HasKey("admid");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("cafeWeb.Models.Computer", b =>
                {
                    b.Property<int>("ComId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("SesId");

                    b.HasKey("ComId");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("cafeWeb.Models.Member", b =>
                {
                    b.Property<int>("meId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccNo");

                    b.Property<DateTime>("DOB");

                    b.Property<string>("Email");

                    b.Property<string>("Phone");

                    b.Property<string>("name");

                    b.HasKey("meId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("cafeWeb.Models.MemberShip", b =>
                {
                    b.Property<int>("AccNo")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MemId");

                    b.Property<string>("Password");

                    b.Property<int>("SecId");

                    b.Property<int>("tSolt");

                    b.HasKey("AccNo");

                    b.ToTable("MemberShips");
                });

            modelBuilder.Entity("cafeWeb.Models.Session", b =>
                {
                    b.Property<int>("SesId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccNo");

                    b.Property<int>("ComId");

                    b.Property<DateTime>("eTime");

                    b.Property<DateTime>("sTime");

                    b.Property<DateTime>("total");

                    b.HasKey("SesId");

                    b.ToTable("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
